# Generated by Django 4.2.2 on 2023-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rules',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.TextField(default='product description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=''),
        ),
    ]
