# Generated by Django 4.2.2 on 2023-07-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_rules_product_shortdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
